### ISSUE TITLE
Threading in grid_nhs.jl produces a large error

### ISSUE THREAD

**Issue by svchb** [trixi-framework/TrixiParticles.jl#451]
```   
 @threaded for cell in collect(keys(hashtable))
        mark_changed_cell!(neighborhood_search, cell, coords_fun)
  end
```

Using `@threaded` here lets dam_break_2d validation fail.

**Comment by efaulhaber** [comment]
Which number of threads did you use? I'll try to reproduce tomorrow. If this loop is really causing the error, and this is not some weird Heisenbug, then that's really bad. That means we have an actual bug in the NHS update, so that some neighbors are missed in the interaction.

So not just different rounding errors from looping in a different order when using threading.

**Comment by svchb** [comment]
I have tested on 1 thread and 8 threads.

**Comment by svchb** [comment]
Has been "fixed" by making the threading optional.
